### ISSUE TITLE
Support for http_proxy and https_proxy 

### ISSUE THREAD

**Issue by jizusun** [Redocly/redocly-vs-code#12]
**What should we improve?**

Make HTTP/HTTPS requests via `http_proxy` and `https_proxy`

**How should we improve it?**
Not known yet

**Why should we improve it?**

In my company, everything has to be through the IT proxy.
After entering my API key and click `Submit`, I can see the following error messages:

```
ar [FetchError]: request to https://api.redoc.ly/registry failed, reason: connect ETIMEDOUT 18.208.49.27:443
    at ClientRequest.<anonymous> (/data/home/jizu/.vscode-server/extensions/redocly.openapi-vs-code-0.2.3/out/server/src/server.js:60:306517)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by roman-sainchuk** [comment]
Hello and thank you for reporting!
We expecting this issue to be fixed after `@redocly/openapi-cli` dependency upgrade to `1.0.0-beta.82`

**Comment by roman-sainchuk** [comment]
Hello, please check out new extension version `0.2.5` and let me know if it is fixed

**Comment by ol1s** [comment]
I'm still getting the following on `0.2.20`

```
request to https://api.redocly.com/registry failed, reason: connect ETIMEDOUT 54.147.100.145:443
```
